# Generated by Django 5.2.16 on 2026-07-17 13:00

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Принят'), ('IN_PROGRESS', 'В работе'), ('READY', 'Сообщили о готовности'), ('DELIVERED', 'Заказ отдан'), ('CANCELLED', 'Отменён')], default='ACCEPTED', max_length=20, verbose_name='Статус')),
                ('production_place', models.CharField(blank=True, max_length=255, verbose_name='Место выполнения')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заказа')),
                ('work_information', models.TextField(verbose_name='Информация о работе')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма к оплате')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Аванс')),
                ('additional_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доплата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-order_date', '-created_at'),
                'indexes': [models.Index(fields=['order_date'], name='orders_order_date_idx'), models.Index(fields=['delivery_date'], name='orders_delivery_date_idx'), models.Index(fields=['status'], name='orders_status_idx'), models.Index(fields=['archived'], name='orders_archived_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('order_number'), condition=models.Q(('archived', False), models.Q(('order_number', ''), _negated=True)), name='uniq_active_order_number_ci'), models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='order_total_amount_non_negative'), models.CheckConstraint(condition=models.Q(('advance_amount__gte', Decimal('0.00'))), name='order_advance_amount_non_negative'), models.CheckConstraint(condition=models.Q(('additional_payment__gte', Decimal('0.00'))), name='order_additional_payment_non_negative')],
            },
        ),
    ]
