# Generated by Django 5.2.16 on 2026-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='production_place',
        ),
    ]
