# Generated by Django 5.2.16 on 2026-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_production_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Новый'), ('WAITING_RESPONSE', 'Ожидаем ответ/предоплату'), ('IN_PROGRESS', 'В работе'), ('READY', 'Позвонили о готовности'), ('DELIVERED', 'Заказ отдан'), ('CANCELLED', 'Отменен')], default='ACCEPTED', max_length=20, verbose_name='Статус'),
        ),
    ]
