# Generated by Django 5.2.16 on 2026-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_active_order_number_ci',
        ),
    ]
