# Generated by Django 5.2.16 on 2026-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_contacts',
            field=models.TextField(blank=True, default='', verbose_name='Исходная запись контактов'),
        ),
    ]
