# Generated by Django 5.2.16 on 2026-07-21 15:13

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_original_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.orders.models.order_attachment_upload_to, verbose_name='файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='заказ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_attachments', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'файл заказа',
                'verbose_name_plural': 'файлы заказов',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['order'], name='order_attach_order_idx'), models.Index(fields=['uploaded_at'], name='order_attach_uploaded_idx')],
            },
        ),
    ]
