# Generated by Django 5.2.16 on 2026-07-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tasks', '0003_archive_completed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='orders.order', verbose_name='заказ'),
        ),
    ]
