# Generated by Django 5.2.16 on 2026-07-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('preferred_channel', models.CharField(blank=True, choices=[('PHONE', 'Телефон'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('MAX', 'MAX'), ('EMAIL', 'Email'), ('OTHER', 'Другое')], max_length=20, verbose_name='Предпочтительный канал связи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source_text', models.TextField(blank=True, verbose_name='Исходная запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('display_name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Телефон'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('MAX', 'MAX'), ('EMAIL', 'Email'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип')),
                ('raw_value', models.CharField(max_length=255, verbose_name='Значение')),
                ('normalized_value', models.CharField(blank=True, max_length=255, verbose_name='Нормализованное значение')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'контакт клиента',
                'verbose_name_plural': 'контакты клиентов',
                'ordering': ('-is_primary', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['display_name'], name='clients_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['preferred_channel'], name='clients_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['archived'], name='clients_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['contact_type'], name='client_contact_type_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['normalized_value'], name='client_contact_norm_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('client',), name='unique_primary_contact_per_client'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_value', ''), _negated=True), fields=('client', 'contact_type', 'normalized_value'), name='unique_contact_value_per_client'),
        ),
    ]
